# Generated by Django 3.2 on 2024-01-31 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('timestampmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.timestampmixin')),
                ('kind', models.CharField(blank=True, choices=[('in', 'وارد'), ('out', 'صادر')], default='in', max_length=35, null=True, verbose_name='نوع المبلغ')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='المبلغ')),
                ('details', models.TextField(blank=True, null=True, verbose_name='التفصيل')),
                ('masterInvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.masterinvoice', verbose_name='الفاتورة')),
            ],
            bases=('client.timestampmixin', models.Model),
        ),
    ]
