# Generated by Django 5.0.3 on 2024-05-07 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_clientsizes_t'),
        ('kazna', '0002_record_classs'),
        ('order', '0006_alter_masterinvoice_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailpayRecord',
            fields=[
                ('timestampmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.timestampmixin')),
                ('classs', models.CharField(blank=True, max_length=35, null=True, verbose_name='تصنيف الدفع')),
                ('paid', models.IntegerField(blank=True, null=True, verbose_name='المبلغ المدفوع')),
                ('remain', models.IntegerField(blank=True, null=True, verbose_name='المبلغ المتبقى')),
                ('masterInvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.masterinvoice', verbose_name='الفاتورة')),
            ],
            bases=('client.timestampmixin', models.Model),
        ),
    ]
