# Generated by Django 3.2 on 2024-05-07 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_clientsizes_t'),
        ('kazna', '0003_detailpayrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailpayrecord',
            name='clientt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='العميل'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detailpayrecord',
            name='classs',
            field=models.CharField(blank=True, default='-', max_length=35, null=True, verbose_name='تصنيف الدفع'),
        ),
    ]
