# Generated by Django 5.0.3 on 2024-04-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0002_alter_img_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='file',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='uploade_imgs/'),
        ),
    ]
