# Generated by Django 3.2 on 2024-01-31 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStampMixin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('timestampmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.timestampmixin')),
                ('FName', models.CharField(blank=True, max_length=15, null=True, verbose_name='الاسم الاول')),
                ('SName', models.CharField(blank=True, max_length=15, null=True, verbose_name='الاسم الثانى')),
                ('TName', models.CharField(blank=True, max_length=15, null=True, verbose_name='الاسم الثالث')),
                ('LName', models.CharField(blank=True, max_length=15, null=True, verbose_name='الاسم الرابع')),
                ('name', models.CharField(blank=True, db_index=True, max_length=60, null=True, verbose_name='الاسم بالكامل')),
                ('kindMale', models.CharField(blank=True, choices=[('male', 'رجالى'), ('female', 'حريمى')], default='male', max_length=10, null=True, verbose_name='نوع العميل')),
                ('book', models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم الدفتر')),
                ('page', models.IntegerField(blank=True, null=True, verbose_name='صفحة رقم')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='رقم التليفون')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='العنوان')),
            ],
            bases=('client.timestampmixin', models.Model),
        ),
        migrations.CreateModel(
            name='ClientSizes',
            fields=[
                ('timestampmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.timestampmixin')),
                ('tall', models.CharField(blank=True, max_length=5, null=True, verbose_name='الطول')),
                ('kom', models.CharField(blank=True, max_length=5, null=True, verbose_name='الكم')),
                ('ktf', models.CharField(blank=True, max_length=5, null=True, verbose_name='الكتف')),
                ('sadr', models.CharField(blank=True, max_length=5, null=True, verbose_name='الصدر')),
                ('leaka', models.CharField(blank=True, max_length=5, null=True, verbose_name='اللياقه')),
                ('kazna', models.CharField(blank=True, max_length=5, null=True, verbose_name='الخزنه')),
                ('atak', models.CharField(blank=True, max_length=5, null=True, verbose_name='الأتك')),
                ('clientS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='client.client')),
            ],
            bases=('client.timestampmixin', models.Model),
        ),
    ]
