# Generated by Django 3.2 on 2023-11-18 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStampMixin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('timestampmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.timestampmixin')),
                ('fName', models.CharField(blank=True, max_length=15, null=True, verbose_name='الاسم الرابع')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='الاسم بالكامل')),
                ('kindMale', models.BooleanField(blank=True, null=True, verbose_name='نوع العميل : ذكر')),
                ('page', models.PositiveIntegerField(blank=True, null=True, verbose_name='صفحة رقم')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='رقم التليفون')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='العنوان')),
            ],
            bases=('client.timestampmixin', models.Model),
        ),
    ]
