# Generated by Django 3.2 on 2023-11-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='الاسم بالكامل'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=11, null=True, unique=True, verbose_name='رقم التليفون'),
        ),
    ]
