# Generated by Django 3.2 on 2023-11-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20231118_0616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='fName',
            new_name='LName',
        ),
        migrations.AddField(
            model_name='client',
            name='FName',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='الاسم الاول'),
        ),
        migrations.AddField(
            model_name='client',
            name='SName',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='الاسم الثانى'),
        ),
        migrations.AddField(
            model_name='client',
            name='TName',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='الاسم الثالث'),
        ),
    ]
