# Generated by Django 5.0.3 on 2024-05-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_clientsizes_t'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='counter',
            field=models.PositiveIntegerField(default=0, verbose_name='رقم العميل'),
        ),
    ]
