# Generated by Django 3.2 on 2023-11-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20231118_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='book',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم الدفتر'),
        ),
        migrations.AlterField(
            model_name='client',
            name='page',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='صفحة رقم'),
        ),
    ]
