# Generated by Django 3.2 on 2023-11-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_client_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='kindMale',
            field=models.CharField(blank=True, choices=[('male', 'رجالى'), ('female', 'حريمى')], max_length=10, null=True, verbose_name='نوع العميل'),
        ),
    ]
