# Generated by Django 3.2 on 2023-11-25 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_client_kindmale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timestampmixin',
            name='is_deleted',
        ),
    ]
