# Generated by Django 3.2 on 2023-11-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20231129_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='kindMale',
            field=models.CharField(blank=True, choices=[('male', 'رجالى'), ('female', 'حريمى')], default='male', max_length=10, null=True, verbose_name='نوع العميل'),
        ),
    ]
