# Generated by Django 3.2 on 2023-12-17 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_client_kindmale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSizes',
            fields=[
                ('timestampmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.timestampmixin')),
                ('tall', models.CharField(blank=True, max_length=5, null=True, verbose_name='الطول')),
                ('kom', models.CharField(blank=True, max_length=5, null=True, verbose_name='الكم')),
                ('ktf', models.CharField(blank=True, max_length=5, null=True, verbose_name='الكتف')),
                ('sadr', models.CharField(blank=True, max_length=5, null=True, verbose_name='الصدر')),
                ('leaka', models.CharField(blank=True, max_length=5, null=True, verbose_name='اللياقه')),
                ('kazna', models.CharField(blank=True, max_length=5, null=True, verbose_name='الخزنه')),
                ('atak', models.CharField(blank=True, max_length=5, null=True, verbose_name='الأتك')),
                ('clientS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='client.client')),
            ],
            bases=('client.timestampmixin', models.Model),
        ),
    ]
