# Generated by Django 3.2 on 2023-12-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_clientsizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestampmixin',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
