# Generated by Django 5.0.3 on 2024-04-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterinvoice',
            name='confirmed',
            field=models.BooleanField(default=False, editable=False, verbose_name='تأكيد الطلب'),
        ),
    ]
