# Generated by Django 5.0.3 on 2024-04-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_masterinvoice_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterinvoice',
            name='confirmed',
        ),
    ]
