# Generated by Django 5.0.3 on 2024-04-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_masterinvoice_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterinvoice',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
