# Generated by Django 5.0.3 on 2024-06-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_masterinvoice_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterinvoice',
            name='old_counter',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
