# Generated by Django 4.2 on 2024-07-29 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_counter'),
        ('order', '0008_paydebit_debit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitOrder',
            fields=[
                ('timestampmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.timestampmixin')),
                ('paid', models.IntegerField(blank=True, null=True, verbose_name='المبلغ المدفوع')),
                ('remain', models.IntegerField(blank=True, null=True, verbose_name='المبلغ المتبقى')),
                ('MasterInvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.masterinvoice', verbose_name='الفاتورة')),
            ],
            bases=('client.timestampmixin', models.Model),
        ),
        migrations.DeleteModel(
            name='Debit',
        ),
    ]
