# Generated by Django 3.2 on 2024-02-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsizes',
            name='t',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='دوران الرقبه'),
        ),
    ]
