# Generated by Django 3.2 on 2023-11-24 13:35

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0006_alter_client_kindmale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True, verbose_name='اسم التصنيف')),
            ],
        ),
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('timestampmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.timestampmixin')),
                ('name', models.CharField(blank=True, max_length=25, null=True, verbose_name='اسم القماش')),
                ('amount', models.CharField(blank=True, max_length=5, null=True, verbose_name='الكمية')),
                ('price', models.CharField(blank=True, max_length=5, null=True, verbose_name='سعر المتر')),
                ('typee', models.CharField(blank=True, db_index=True, max_length=25, null=True, verbose_name='الاسم بالكامل')),
                ('color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='لون القماش')),
                ('classs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storge.classs', verbose_name='التصنيف')),
            ],
            bases=('client.timestampmixin', models.Model),
        ),
    ]
