# Generated by Django 3.2 on 2024-01-31 15:01

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم التصنيف')),
            ],
        ),
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('timestampmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.timestampmixin')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم القماش')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الكمية')),
                ('price', models.CharField(blank=True, max_length=5, null=True, verbose_name='سعر المتر')),
                ('typee', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='النوع')),
                ('color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='لون القماش')),
                ('classs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storge.classs', verbose_name='التصنيف')),
            ],
            bases=('client.timestampmixin', models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCloth',
            fields=[
                ('timestampmixin_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='client.timestampmixin')),
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم القماش')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الكمية')),
                ('price', models.CharField(blank=True, max_length=5, null=True, verbose_name='سعر المتر')),
                ('typee', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='النوع')),
                ('color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='لون القماش')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('classs', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='storge.classs', verbose_name='التصنيف')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical cloth',
                'verbose_name_plural': 'historical cloths',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ClothRecord',
            fields=[
                ('timestampmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.timestampmixin')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الكمية')),
                ('typee', models.CharField(blank=True, choices=[('inside', 'وارد'), ('outside', 'صادر')], default='inside', max_length=10, null=True, verbose_name='نوع السجل')),
                ('clothh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='storge.cloth', verbose_name='القماش')),
            ],
            bases=('client.timestampmixin', models.Model),
        ),
    ]
