# Generated by Django 3.2 on 2024-02-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='historicalcloth',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='الكمية'),
        ),
    ]
