# Generated by Django 3.2 on 2023-11-24 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_client_kindmale'),
        ('storge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classs',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم التصنيف'),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم القماش'),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='typee',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='النوع'),
        ),
        migrations.CreateModel(
            name='ClothRecord',
            fields=[
                ('timestampmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.timestampmixin')),
                ('amount', models.CharField(blank=True, max_length=5, null=True, verbose_name='الكمية')),
                ('clothh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storge.cloth', verbose_name='القماش')),
            ],
            bases=('client.timestampmixin', models.Model),
        ),
    ]
