# Generated by Django 3.2 on 2023-11-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0002_auto_20231124_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothrecord',
            name='typee',
            field=models.CharField(blank=True, choices=[('export', 'صادر'), ('import', 'وارد')], max_length=10, null=True, verbose_name='نوع السجل'),
        ),
    ]
