# Generated by Django 3.2 on 2023-11-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0003_clothrecord_typee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothrecord',
            name='typee',
            field=models.CharField(blank=True, choices=[('outside', 'صادر'), ('inside', 'وارد')], max_length=10, null=True, verbose_name='نوع السجل'),
        ),
    ]
