# Generated by Django 3.2 on 2023-11-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0006_historicalcloth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothrecord',
            name='typee',
            field=models.CharField(blank=True, choices=[('inside', 'وارد'), ('outside', 'صادر')], max_length=10, null=True, verbose_name='نوع السجل'),
        ),
        migrations.AlterField(
            model_name='historicalcloth',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
