# Generated by Django 3.2 on 2023-11-30 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0007_auto_20231129_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothrecord',
            name='clothh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='storge.cloth', verbose_name='القماش'),
        ),
        migrations.AlterField(
            model_name='clothrecord',
            name='typee',
            field=models.CharField(blank=True, choices=[('inside', 'وارد'), ('outside', 'صادر')], default='inside', max_length=10, null=True, verbose_name='نوع السجل'),
        ),
    ]
