# Generated by Django 3.2 on 2023-12-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0008_auto_20231130_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcloth',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
