# Generated by Django 3.2 on 2024-01-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=75, null=True, verbose_name='اسم الصورة')),
                ('kind', models.CharField(blank=True, choices=[('male', 'رجالى'), ('femal', 'حريمى')], default='male', max_length=35, null=True, verbose_name='تصنيف الصورة')),
            ],
        ),
    ]
