# Generated by Django 3.2 on 2024-02-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='file',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='imgs/'),
        ),
    ]
