# Generated by Django 3.2 on 2024-01-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='imgs/'),
        ),
    ]
