# Generated by Django 3.2 on 2024-01-23 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0002_img_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=75, null=True, verbose_name='تصنيف الصورة')),
            ],
        ),
        migrations.RemoveField(
            model_name='img',
            name='kind',
        ),
        migrations.AddField(
            model_name='img',
            name='sort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='img.sort', verbose_name='تصنيف الصورة'),
        ),
    ]
