# Generated by Django 3.2 on 2024-01-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0003_auto_20240123_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='kind',
            field=models.CharField(blank=True, choices=[('male', 'رجالى'), ('femal', 'حريمى')], default='male', max_length=10, null=True, verbose_name='نوع العميل'),
        ),
    ]
