# Generated by Django 3.2 on 2023-12-17 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0010_clientsizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterInvoice',
            fields=[
                ('timestampmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.timestampmixin')),
                ('invoiceType', models.CharField(blank=True, choices=[('قماش الدكان-رجالى', 'قماش الدكان-رجالى'), ('قماش الدكان-حريمى', 'قماش الدكان-حريمى'), ('قماش خارجى-رجالى', 'قماش خارجى-رجالى'), ('قماش خارجى-حريمى', 'قماش خارجى-حريمى'), ('بيع قماش', 'بيع قماش')], default='قماش الدكان-رجالى', max_length=35, null=True, verbose_name='نوع الطلب')),
                ('clientMI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_invoices', to='client.client')),
            ],
            bases=('client.timestampmixin', models.Model),
        ),
    ]
