# Generated by Django 3.2 on 2024-01-31 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('storge', '0001_initial'),
        ('img', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterInvoice',
            fields=[
                ('timestampmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.timestampmixin')),
                ('counter', models.PositiveIntegerField(default=1, editable=False)),
                ('invoiceType', models.CharField(blank=True, choices=[('قماش الدكان-رجالى', 'قماش الدكان-رجالى'), ('قماش الدكان-حريمى', 'قماش الدكان-حريمى'), ('قماش خارجى-رجالى', 'قماش خارجى-رجالى'), ('قماش خارجى-حريمى', 'قماش خارجى-حريمى'), ('بيع قماش', 'بيع قماش')], default='قماش الدكان-رجالى', max_length=35, null=True, verbose_name='نوع الطلب')),
                ('clientMI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_invoices', to='client.client', verbose_name='العميل')),
            ],
            bases=('client.timestampmixin', models.Model),
        ),
        migrations.CreateModel(
            name='DetailedOrder',
            fields=[
                ('timestampmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.timestampmixin')),
                ('name', models.CharField(blank=True, max_length=90, null=True, verbose_name='اسم الطلب')),
                ('used', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='الكمية المستخدمة')),
                ('details', models.TextField(blank=True, null=True, verbose_name='التفصيل')),
                ('clothD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storge.cloth', verbose_name='القماش')),
                ('img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='img.img', verbose_name='الصورة')),
                ('masterInvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.masterinvoice', verbose_name='الفاتورة')),
            ],
            bases=('client.timestampmixin', models.Model),
        ),
        migrations.CreateModel(
            name='Deliverd',
            fields=[
                ('timestampmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.timestampmixin')),
                ('kind', models.CharField(blank=True, choices=[('withCard', 'تسليم بالكارت'), ('withoutCard', 'تسليم بدون كارت')], default='بالكارت', max_length=35, null=True, verbose_name='نوع التسليم')),
                ('reciever', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المستلم')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم التليفون')),
                ('relation', models.CharField(blank=True, max_length=100, null=True, verbose_name='صله القرابة')),
                ('naId', models.CharField(blank=True, max_length=14, null=True, verbose_name='الرقم القومى')),
                ('img', models.FileField(blank=True, null=True, upload_to='deliverd/', verbose_name='صورة الرقم القومى')),
                ('masterInvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.masterinvoice', verbose_name='الفاتورة')),
            ],
            bases=('client.timestampmixin', models.Model),
        ),
        migrations.CreateModel(
            name='basicInvoiceInfo',
            fields=[
                ('timestampmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.timestampmixin')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='المبلغ الإجمالى')),
                ('paid', models.IntegerField(blank=True, null=True, verbose_name='المبلغ المدفوع')),
                ('remain', models.IntegerField(blank=True, null=True, verbose_name='المبلغ المتبقى')),
                ('receve_date', models.DateField(blank=True, null=True)),
                ('statue', models.CharField(blank=True, choices=[('unknwon', 'غير محدد'), ('sent', 'تم ارسالها الى المشغل'), ('done', 'جاهز للتسليم'), ('delivered', 'تم التسليم'), ('returned', 'مرتجع'), ('doneAgain', 'تسليم بعد المرتجع')], default='unknwon', max_length=35, null=True, verbose_name='حالة الطلب')),
                ('masterInvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.masterinvoice', verbose_name='الفاتورة')),
            ],
            bases=('client.timestampmixin', models.Model),
        ),
    ]
