# Generated by Django 3.2 on 2023-12-17 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0008_auto_20231130_2039'),
        ('client', '0010_clientsizes'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterinvoice',
            name='clientMI',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_invoices', to='client.client', verbose_name='العميل'),
        ),
        migrations.CreateModel(
            name='DetailedOrder',
            fields=[
                ('timestampmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.timestampmixin')),
                ('name', models.CharField(blank=True, max_length=35, null=True, verbose_name='اسم الطلب')),
                ('used', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='الكمية المستخدمة')),
                ('details', models.TextField(blank=True, null=True, verbose_name='التفصيل')),
                ('clothD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storge.cloth', verbose_name='القماش')),
            ],
            bases=('client.timestampmixin', models.Model),
        ),
    ]
