# Generated by Django 3.2 on 2023-12-18 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20231217_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedorder',
            name='masterInvoice',
            field=models.ForeignKey(default=966, on_delete=django.db.models.deletion.CASCADE, to='order.masterinvoice', verbose_name='الفاتورة'),
            preserve_default=False,
        ),
    ]
