# Generated by Django 3.2 on 2023-12-25 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_clientsizes'),
        ('order', '0003_detailedorder_masterinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailedorder',
            name='name',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='اسم الطلب'),
        ),
        migrations.CreateModel(
            name='basicInvoiceInfo',
            fields=[
                ('timestampmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.timestampmixin')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='المبلغ الإجمالى')),
                ('paid', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='المبلغ المدفوع')),
                ('remain', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='المبلغ المتبقى')),
                ('masterInvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.masterinvoice', verbose_name='الفاتورة')),
            ],
            bases=('client.timestampmixin', models.Model),
        ),
    ]
