# Generated by Django 3.2 on 2023-12-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20231225_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinvoiceinfo',
            name='paid',
            field=models.IntegerField(blank=True, null=True, verbose_name='المبلغ المدفوع'),
        ),
        migrations.AlterField(
            model_name='basicinvoiceinfo',
            name='remain',
            field=models.IntegerField(blank=True, null=True, verbose_name='المبلغ المتبقى'),
        ),
        migrations.AlterField(
            model_name='basicinvoiceinfo',
            name='total',
            field=models.IntegerField(blank=True, null=True, verbose_name='المبلغ الإجمالى'),
        ),
    ]
