# Generated by Django 3.2 on 2023-12-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20231225_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterinvoice',
            name='counter',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
