# Generated by Django 3.2 on 2024-01-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_masterinvoice_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinvoiceinfo',
            name='receve_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
