# Generated by Django 4.2 on 2024-07-29 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_masterinvoice_old_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='payDebit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.IntegerField(blank=True, null=True, verbose_name='المبلغ المدفوع')),
                ('remain', models.IntegerField(blank=True, null=True, verbose_name='المبلغ المتبقى')),
                ('MasterInvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.masterinvoice', verbose_name='الفاتورة')),
            ],
        ),
        migrations.CreateModel(
            name='Debit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.IntegerField(blank=True, null=True, verbose_name='المبلغ المدفوع')),
                ('remain', models.IntegerField(blank=True, null=True, verbose_name='المبلغ المتبقى')),
                ('MasterInvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.masterinvoice', verbose_name='الفاتورة')),
            ],
        ),
    ]
