# Generated by Django 3.2 on 2024-01-25 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0004_img_kind'),
        ('order', '0008_alter_detailedorder_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedorder',
            name='img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='img.img', verbose_name='رقم الصورة'),
        ),
    ]
