# Generated by Django 3.2 on 2024-01-26 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0004_img_kind'),
        ('order', '0009_detailedorder_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinvoiceinfo',
            name='statue',
            field=models.CharField(blank=True, choices=[('unknwon', 'غير محدد'), ('sent', 'تم ارسالها الى المشغل'), ('done', 'جاهز للتسليم'), ('delivered', 'تم التسليم')], default='قماش الدكان-رجالى', max_length=35, null=True, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='detailedorder',
            name='img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='img.img', verbose_name='الصورة'),
        ),
    ]
