# Generated by Django 4.2 on 2024-09-16 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_debitpay'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payDebit',
        ),
    ]
