# Generated by Django 3.2 on 2024-01-29 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_timestampmixin_is_deleted'),
        ('order', '0011_alter_basicinvoiceinfo_statue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverd',
            fields=[
                ('timestampmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.timestampmixin')),
                ('reciever', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المستلم')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم التليفون')),
                ('relation', models.CharField(blank=True, max_length=100, null=True, verbose_name='صله القرابة')),
                ('naId', models.CharField(blank=True, max_length=14, null=True, verbose_name='الرقم القومى')),
                ('img', models.FileField(blank=True, null=True, upload_to='deliverd/', verbose_name='صورة الرقم القومى')),
                ('masterInvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.masterinvoice', verbose_name='الفاتورة')),
            ],
            bases=('client.timestampmixin', models.Model),
        ),
    ]
