# Generated by Django 4.2 on 2024-11-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_delete_paydebit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinvoiceinfo',
            name='statue',
            field=models.CharField(blank=True, choices=[('unknwon', 'غير محدد'), ('sent', 'تم ارسالها الى المشغل'), ('done', 'جاهز للتسليم'), ('delivered', 'تم التسليم'), ('returned', 'مرتجع'), ('doneAgain', 'تسليم بعد المرتجع'), ('urgent', 'مستعجل'), ('late', 'متأخر')], default='unknwon', max_length=35, null=True, verbose_name='حالة الطلب'),
        ),
    ]
