# Generated by Django 3.2 on 2024-01-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_deliverd'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverd',
            name='kind',
            field=models.CharField(blank=True, choices=[('withCard', 'تسليم بالكارت'), ('withoutCard', 'تسليم بدون كارت')], default='بالكارت', max_length=35, null=True, verbose_name='نوع التسليم'),
        ),
    ]
