# Generated by Django 3.2 on 2024-02-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='classs',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='تصنيف الدفع'),
        ),
    ]
