# Generated by Django 3.2 on 2024-01-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='المبلغ'),
        ),
    ]
