# Generated by Django 3.2 on 2024-01-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazna', '0002_record_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='المبلغ'),
        ),
    ]
