# Generated by Django 3.2 on 2024-01-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazna', '0003_alter_record_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='المبلغ'),
        ),
    ]
