# Generated by Django 4.2.3 on 2024-06-23 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_counter'),
        ('kazna', '0004_auto_20240507_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('timestampmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.timestampmixin')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='مسمى الدفع')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='المبلغ')),
                ('details', models.TextField(blank=True, null=True, verbose_name='التفصيل')),
            ],
            bases=('client.timestampmixin', models.Model),
        ),
    ]
